#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=./lib/common.sh
. "${script_dir}/lib/common.sh"

usage() {
  cat <<'EOF'
Usage: scripts/setup.sh [--env-file PATH] [--output PATH] [--target PATH]

Interactive setup for creating a local .env file. The env/template workflow
remains the primary source of truth; this script is a convenience layer that
collects values step by step and writes them into an env file.
EOF
}

env_file="${repo_root}/.env"
output_file="${repo_root}/.msmtprc.generated"
target_path="${HOME}/.msmtprc"

while [ $# -gt 0 ]; do
  case "$1" in
    --env-file)
      [ $# -ge 2 ] || die "--env-file requires a value"
      env_file="$2"
      shift 2
      ;;
    --output)
      [ $# -ge 2 ] || die "--output requires a value"
      output_file="$2"
      shift 2
      ;;
    --target)
      [ $# -ge 2 ] || die "--target requires a value"
      target_path="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

prompt_value() {
  local prompt_text="$1"
  local default_value="${2:-}"
  local response

  if [ -n "$default_value" ]; then
    printf '%s [%s]: ' "$prompt_text" "$default_value" >&2
  else
    printf '%s: ' "$prompt_text" >&2
  fi

  IFS= read -r response
  if [ -z "$response" ]; then
    response="$default_value"
  fi

  printf '%s\n' "$response"
}

prompt_required() {
  local prompt_text="$1"
  local default_value="${2:-}"
  local response=""

  while [ -z "$response" ]; do
    response="$(prompt_value "$prompt_text" "$default_value")"
    if [ -z "$response" ]; then
      printf 'A value is required.\n' >&2
    fi
  done

  printf '%s\n' "$response"
}

prompt_yes_no() {
  local prompt_text="$1"
  local default_value="$2"
  local suffix response normalized

  case "$default_value" in
    yes)
      suffix="Y/n"
      ;;
    no)
      suffix="y/N"
      ;;
    *)
      die "Unsupported default for yes/no prompt: $default_value"
      ;;
  esac

  while true; do
    printf '%s [%s]: ' "$prompt_text" "$suffix" >&2
    IFS= read -r response
    if [ -z "$response" ]; then
      response="$default_value"
    fi

    normalized="$(printf '%s' "$response" | tr '[:upper:]' '[:lower:]')"
    case "$normalized" in
      y | yes)
        printf 'yes\n'
        return 0
        ;;
      n | no)
        printf 'no\n'
        return 0
        ;;
    esac

    printf 'Please answer yes or no.\n' >&2
  done
}

default_secret_method() {
  case "$(uname -s)" in
    Darwin)
      printf 'keychain\n'
      ;;
    *)
      printf 'gpg\n'
      ;;
  esac
}

prompt_secret_method() {
  local response default_value normalized

  default_value="$(default_secret_method)"

  printf 'Setup profiles:\n' >&2
  printf '  1. keychain\n' >&2
  printf '  2. gpg\n' >&2
  printf '  3. password_file\n' >&2
  printf '  4. command\n' >&2

  while true; do
    response="$(prompt_value "Choose a secret method" "$default_value")"
    normalized="$(printf '%s' "$response" | tr '[:upper:]' '[:lower:]' | tr '-' '_')"
    case "$normalized" in
      1 | keychain)
        printf 'keychain\n'
        return 0
        ;;
      2 | gpg)
        printf 'gpg\n'
        return 0
        ;;
      3 | password_file)
        printf 'password_file\n'
        return 0
        ;;
      4 | command)
        printf 'command\n'
        return 0
        ;;
    esac

    printf 'Choose one of: keychain, gpg, password_file, command.\n' >&2
  done
}

prompt_install_mode() {
  local response normalized

  while true; do
    response="$(prompt_value "Install mode" "copy")"
    normalized="$(printf '%s' "$response" | tr '[:upper:]' '[:lower:]')"
    case "$normalized" in
      copy | symlink)
        printf '%s\n' "$normalized"
        return 0
        ;;
    esac

    printf 'Choose one of: copy, symlink.\n' >&2
  done
}

write_env_file() {
  local destination="$1"

  mkdir -p "$(dirname "$destination")"
  umask 077
  {
    printf '# Generated by scripts/setup.sh.\n'
    printf '# Review and edit as needed before rerendering.\n'
    write_env_assignment MSMTP_ACCOUNT_NAME "$MSMTP_ACCOUNT_NAME"
    write_env_assignment MSMTP_HOST "$MSMTP_HOST"
    write_env_assignment MSMTP_PORT "$MSMTP_PORT"
    write_env_assignment MSMTP_FROM "$MSMTP_FROM"
    write_env_assignment MSMTP_USER "$MSMTP_USER"
    write_env_assignment MSMTP_AUTH "$MSMTP_AUTH"
    write_env_assignment MSMTP_TLS "$MSMTP_TLS"
    write_env_assignment MSMTP_TLS_STARTTLS "$MSMTP_TLS_STARTTLS"
    write_env_assignment MSMTP_TLS_CERTCHECK "$MSMTP_TLS_CERTCHECK"
    write_env_assignment MSMTP_SET_DEFAULT "$MSMTP_SET_DEFAULT"
    write_env_assignment MSMTP_LOGFILE "$MSMTP_LOGFILE"
    write_env_assignment MSMTP_TLS_TRUST_FILE "$MSMTP_TLS_TRUST_FILE"
    write_env_assignment MSMTP_TLS_FINGERPRINT "$MSMTP_TLS_FINGERPRINT"
    write_env_assignment MSMTP_SECRET_METHOD "$MSMTP_SECRET_METHOD"
    write_env_assignment MSMTP_KEYCHAIN_SERVICE "$MSMTP_KEYCHAIN_SERVICE"
    write_env_assignment MSMTP_KEYCHAIN_ACCOUNT "$MSMTP_KEYCHAIN_ACCOUNT"
    write_env_assignment MSMTP_GPG_FILE "$MSMTP_GPG_FILE"
    write_env_assignment MSMTP_PASSWORD_FILE "$MSMTP_PASSWORD_FILE"
    write_env_assignment MSMTP_PASSWORDEVAL_COMMAND "$MSMTP_PASSWORDEVAL_COMMAND"
  } > "$destination"
  chmod 600 "$destination"
}

if [ -e "$env_file" ]; then
  die "Refusing to overwrite existing file: $env_file"
fi

printf 'Interactive msmtp setup\n' >&2
printf 'This writes %s and keeps the env/template workflow as the source of truth.\n\n' "$env_file" >&2

MSMTP_ACCOUNT_NAME="$(prompt_required "Account name" "default")"
MSMTP_HOST="$(prompt_required "SMTP host")"
MSMTP_PORT="$(prompt_required "SMTP port" "587")"
MSMTP_FROM="$(prompt_required "From address")"
MSMTP_USER="$(prompt_required "Username" "$MSMTP_FROM")"
MSMTP_SECRET_METHOD="$(prompt_secret_method)"

MSMTP_KEYCHAIN_SERVICE=""
MSMTP_KEYCHAIN_ACCOUNT=""
MSMTP_GPG_FILE=""
MSMTP_PASSWORD_FILE=""
MSMTP_PASSWORDEVAL_COMMAND=""

case "$MSMTP_SECRET_METHOD" in
  keychain)
    MSMTP_KEYCHAIN_SERVICE="$(prompt_required "Keychain service" "$MSMTP_HOST")"
    MSMTP_KEYCHAIN_ACCOUNT="$(prompt_required "Keychain account" "$MSMTP_USER")"
    ;;
  gpg)
    MSMTP_GPG_FILE="$(prompt_required "Path to the GPG-encrypted password file")"
    ;;
  password_file)
    MSMTP_PASSWORD_FILE="$(prompt_required "Path to the password file")"
    ;;
  command)
    MSMTP_PASSWORDEVAL_COMMAND="$(prompt_required "Custom passwordeval command")"
    ;;
esac

if [ "$(prompt_yes_no "Enable SMTP auth" "yes")" = "yes" ]; then
  MSMTP_AUTH="on"
else
  MSMTP_AUTH="off"
fi

if [ "$(prompt_yes_no "Enable TLS" "yes")" = "yes" ]; then
  MSMTP_TLS="on"
else
  MSMTP_TLS="off"
fi

if [ "$(prompt_yes_no "Enable STARTTLS" "yes")" = "yes" ]; then
  MSMTP_TLS_STARTTLS="on"
else
  MSMTP_TLS_STARTTLS="off"
fi

if [ "$(prompt_yes_no "Verify TLS certificates" "yes")" = "yes" ]; then
  MSMTP_TLS_CERTCHECK="on"
else
  MSMTP_TLS_CERTCHECK="off"
fi

if [ "$(prompt_yes_no "Set this as the default account" "yes")" = "yes" ]; then
  MSMTP_SET_DEFAULT="true"
else
  MSMTP_SET_DEFAULT="false"
fi

MSMTP_LOGFILE="$(prompt_value "Log file path (optional)")"
MSMTP_TLS_TRUST_FILE="$(prompt_value "TLS trust file path (optional)")"
MSMTP_TLS_FINGERPRINT="$(prompt_value "TLS fingerprint (optional)")"

write_env_file "$env_file"

printf 'Created %s\n' "$env_file"

if [ "$(prompt_yes_no "Render and install ~/.msmtprc now" "no")" = "yes" ]; then
  install_mode="$(prompt_install_mode)"
  "${repo_root}/scripts/install.sh" \
    --env-file "$env_file" \
    --output "$output_file" \
    --target "$target_path" \
    --mode "$install_mode"
  exit 0
fi

printf 'Next steps:\n'
printf '  1. Review %s.\n' "$env_file"
printf '  2. Run make test.\n'
printf '  3. Run make render or make install.\n'
